### ISSUE TITLE
Got an error when I install this

### ISSUE THREAD

**Issue by gilbert-hop** [CartThrob/CartThrobPaymentGatewaySamples#3]
PHP 8.0
EE 6.3.5

Class "Cartthrob_payment_gateway" not found
user/addons/cartthrob_sample_gateway/src/Cartthrob_sample_gateway.php:5

Stack Trace: Please include when reporting this error
#0 user/addons/cartthrob_sample_gateway/vendor/composer/ClassLoader.php(444): include()
#1 user/addons/cartthrob_sample_gateway/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('...')
#2 user/addons/cartthrob/src/Services/PluginService.php(51): Composer\Autoload\ClassLoader->loadClass('Cartthrob_sampl...')
#3 user/addons/cartthrob_sample_gateway/ext.cartthrob_sample_gateway.php(65): CartThrob\Services\PluginService->register('Cartthrob_sampl...')
#4 ee/legacy/libraries/Extensions.php(203): Cartthrob_Sample_Gateway_ext->cartthrob_boot()
#5 ee/legacy/libraries/Extensions.php(108): EE_Extensions->call_class('Cartthrob_sampl...', 'cartthrob_boot', Array, Array)
#6 user/addons/cartthrob/ext.cartthrob.php(421): EE_Extensions->call('cartthrob_boot')

**Comment by smaida** [comment]
@gilbert-hop Which version of CartThrob are you using?

**Comment by gilbert-hop** [comment]
CartThrob 7.0.0.

**Comment by eric-lamb62** [comment]
I've updated all the branches with the 7.0 usage (which should be backwards compatible with 6). You can either do a pull on the code, or if you've already started work on your custom version, here are the 2 changes you need:

https://github.com/CartThrob/CartThrobPaymentGatewaySamples/commit/9f9a0850f7df4f8f8e0af052ebb1e6628e0f38b9

Can you kick the tires and let me know how it goes?

**Comment by gilbert-hop** [comment]
Hey that worked. I created 3 stripe gateways (tied to different accounts) using this method. Can you please shed some light on how to enable Google Pay? When I put `<div id="payment-element"></div>` I only get the credit card views. Thanks!

**Comment by smaida** [comment]
@gilbert-hop Is Google Pay enabled in Stripe? In my tests, I see Google Pay when I'm in Chrome. I believe it only works with the Payment Element. https://stripe.com/docs/payments/payment-element

**Comment by gilbert-hop** [comment]
Hello @smaida, I am using Payment Element. I'm having difficulty locating the stripe settings to enable Google Play. 
It could be that I'm in the local environment.

**Comment by gilbert-hop** [comment]
Actually, I do see it turned on in my /settings/payment_methods

**Comment by smaida** [comment]
Yep. It should be https://dashboard.stripe.com/settings/payment_methods in Stripe itself.

**Comment by smaida** [comment]
You may want to check this
https://stripe.com/docs/js/elements_object/create_payment_element#payment_element_create-options-wallets

**Comment by gilbert-hop** [comment]
Does it work in your local environment as well? I wonder if that's the reason mine is not showing up. I'm going to put this on the staging server and see.
On a non-related topic... do you have an example of how to quickly switch payment gateway with one button click and submit the payment right after that? I'm trying to build the payment form with Stripe Payment Element but want to show a Paypal button that the user can click and initiate the payment that way.
Or would you suggest I just create a custom payment gateway that will initialize both payment gateways simultaneously instead of toggling between them? Please let me know if you wish for these questions to be in a ticket in the support queue.

**Comment by smaida** [comment]
<img width="1140" alt="Screen Shot 2022-09-29 at 11 42 48 PM" src="https://user-images.githubusercontent.com/999478/193185536-5e6cb02d-4a3f-4933-9ea6-6fbee4cfc90f.png">
<img width="1012" alt="Screen Shot 2022-09-29 at 11 42 45 PM" src="https://user-images.githubusercontent.com/999478/193185541-32e7c063-223a-4c1f-8ff2-160130292625.png">

Google Pay is working for me locally (in Chrome) with the out-of-the-box gateway. Are you in Chrome?

I don't think we have current documentation for using the PayPal button on the same page as Stripe. @mithra62?

**Comment by gilbert-hop** [comment]
Hey @smaida, I put it on the staging site and now the google pay button is showing. I also "combined" the 2 payment gateway (Paypal and stripe) into one custom gateway. However, I'm getting some payment issues with Stripe regarding the CartthrobTokenizer properties payment-intent-id, client-secret, payment-method-id are not passed to the custom gateway charge function. Can you share your billing HTML? Do you just have `<div id="payment-element"></div>` or are there any other things we need to do?

**Comment by eric-lamb62** [comment]
@gilbert-hop yeah, pretty much. For sanity, we moved all the view level code into individual view scripts within CartThrob. You should be able to find all the UI code for the gateways within the `views/payment_gateways` folder. Should be named appropriately. 

`embedded_fields.php` is the data contained within the form tag
`form_extra` is the JS code to process the form submission

**Comment by eric-lamb62** [comment]
Be sure to checkout the data being submitted (usually hidden fields) by each gateway

**Comment by gilbert-hop** [comment]
Hey @mithra62, I am using the `{exp:cartthrob:checkout_form}` and the embedded fields HTML are not added to the form in my template. I then copied the content from embedded_fields to my template but still can't get the tokenizer properties to pass to the charge() function. Do I need to create the 3 properties payment-intent-id, client-secret, payment-method-id as hidden inputs?

**Comment by smaida** [comment]
@gilbert-hop Are you able to give me access?

**Comment by gilbert-hop** [comment]
@smaida sure I'll send you via email.

**Comment by gilbert-hop** [comment]
I also tried stripe_payments and got the same error: Your payment failed: Failed: Stripe Payment Details are missing from POST payload :(

This is what I have in the checkout_form:
```
<div class="control-group" style="margin:auto;width:100%">
                            <div id="payment-request-button">
                                <!-- A Stripe Element will be inserted here. -->
                            </div>
                            <!-- placeholder for Elements -->
                            <div id="payment-element">
                                <!-- Elements will create form elements here -->
                            </div>
                            <div id="error-message">
                                <!-- Display error message to your customers here -->
                            </div>
                        </div>
```

**Comment by gilbert-hop** [comment]
@smaida I had another look and it seems like the `CartthrobTokenizer.onSubmit()` in form_extra.php is not firing when the checkout form is submitted. Maybe my CartthrobTokenizer is not properly initialized? Is there any class/id that the form needs to have? Can you share your checkout billing HTML, and I'll create a blank template to test if things are getting called correctly?

**Comment by gilbert-hop** [comment]
I got it working by changing to `CartthrobTokenizer.onSubmit = () => { // same things }` and then instead of submitting the form I did `CartthrobTokenizer.onSubmit()` and then call the form submit function after `CartthrobTokenizer.onSuccess`.
